name: flutter_codelab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.9.0
  printing: ^5.14.2
  intl: ^0.20.2
  htmltopdfwidgets: ^1.1.3
  pdf: ^3.11.3

  markdown: ^7.3.0
  flutter_markdown: ^0.7.5
  flutter_widget_from_html: ^0.17.1
  flutter_highlight: ^0.7.0
  markdown_widget: ^2.3.2+8
  desktop_drop: ^0.7.0
  google_fonts: ^6.3.2
  flutter_markdown_plus: ^1.0.5
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  file_picker: ^10.3.6
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4
  
  flutter_inappwebview: ^6.1.5
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  dotted_border: ^3.1.0
  cross_file: ^0.3.5+1

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  json_rpc_2: ^4.0.0
  stack_trace: ^1.12.1
  web: ^1.1.1
  encrypt: ^5.0.3
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/js/
    - assets/a2.png
    - assets/a3.png
    - assets/unity/
    - assets/CodePlay.png
    - assets/www/
    - assets/www/pictures/
    - assets/www/pictures/JS/
    - assets/www/3.1.9 Atur Cara lnteraktif yang Mengandungi Pengisytiharan Data, Struktur Kawalan, Procedure dan Function serta Tatasusunan/
    - assets/www/3.2.2 Penghasilan dan Penyimpanan Data dalam Fail Teks (.txt)/
    - assets/www/3.2.3 Penggunaan Bahasa Penskripan Pelayan untuk Membina Laman Web yang Unik bagi Setiap Pengguna/
    - assets/www/3.2.4 Penggunaan Data yang Diimport daripada Fail Teks untuk Menyelesaikan Masalah/
    - assets/www/3.2.5 Menggunakan Data yang Diimport dari Fail Pangkalan Data untuk Menyelesaikan Masalah/
    - assets/www/3.2.8 Melaksanakan Beberapa Bentuk Pertanyaan (Ouery) Pangkalan Data/
    - assets/www/3.2.9 Membina Daftar (Sign Up) dan Log Masuk (Login) dalam Suatu Laman Web/
    - assets/txt/
